---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-documentui

data:
  apihost: documentservice:8080

---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: documentui

spec:
  replicas: 1
  revisionHistoryLimit: 3

  template:
    metadata:
      labels:
        app: documentui

    spec:

      containers:
        - name: documentui
          image: codecentric/documentui:1.0

          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-documentui
                  key: apihost

          ports:
            - name: server
              containerPort: 3000
              protocol: TCP

          resources:
            limits:
              memory: 1000Mi
              cpu: 0.3

            requests:
              memory: 50Mi
              cpu: 0.1

---
kind: Service
apiVersion: v1

metadata:
  name: documentui

spec:
  selector:
    app: documentui

  type: LoadBalancer

  ports:
    - name: api
      port: 3000
      targetPort: 3000

