---
kind: Secret
apiVersion: v1
metadata:
  name: config-documentservice

stringData:
  application.yaml: |
    spring:
      data:
        elasticsearch:
          cluster-nodes: "elasticsearch:9300"

---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: documentservice

spec:
  replicas: 1
  revisionHistoryLimit: 3

  template:
    metadata:
      labels:
        app: documentservice

    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: config-documentservice

      containers:
        - name: documentservice
          image: codecentric/documentservice:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: JAVA_OPTS
              value: "-Xmx256m"
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"

          ports:
            - name: api
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              memory: 200Mi
              cpu: 0.7

            requests:
              memory: 100Mi
              cpu: 0.2

          volumeMounts:
            - name: config-volume
              mountPath: /config

---
kind: Service
apiVersion: v1

metadata:
  name: documentservice

spec:
  selector:
    app: documentservice

  type: ClusterIP

  ports:
    - name: api
      port: 8080
      targetPort: 8080

