kind: Deployment
apiVersion: apps/v1beta2

metadata:
  name: documentui

spec:
  replicas: 1

  selector:
    matchLabels:
      app: documentui
  template:
    metadata:
      labels:
        app: documentui

    spec:

      containers:
        - name: documentui
          image: codecentric/informatik-aktuell-usingk8s-documentui:1.0

          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-documentui
                  key: apihost

          ports:
            - name: server
              containerPort: 3000
              protocol: TCP

          resources:
            limits:
              memory: 100Mi
              cpu: 0.2
            requests:
              memory: 50Mi
              cpu: 0.05
