kind: Deployment
apiVersion: apps/v1beta2

metadata:
  name: documentservice

spec:
  replicas: 1

  selector:
    matchLabels:
      app: documentservice
  template:
    metadata:
      labels:
        app: documentservice

    spec:
      containers:
        - name: documentservice
          image: codecentric/informatik-aktuell-usingk8s-documentservice:1.0

          env:
            - name: JAVA_OPTS
              value: "-Xmx256m"
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"

          ports:
            - name: api
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              memory: 300Mi
              cpu: 0.2
            requests:
              memory: 100Mi
              cpu: 0.1

          volumeMounts:
            - name: config-volume
              mountPath: /config

      volumes:
        - name: config-volume
          secret:
            secretName: config-documentservice
