kind: Service
apiVersion: v1

metadata:
  name: elasticsearch

spec:
  selector:
    app: elasticsearch

  # headless service
  type: ClusterIP
  clusterIP: None

  ports:
    - name: cluster
      port: 9300
      targetPort: 9300
